user:
    resource: "@UserBundle/Controller/"
    type:     annotation

post:
    resource: "@PostBundle/Controller/"
    type:     annotation

app:
    resource: '@AppBundle/Controller/'
    type: annotation
