services:
#   Controllers
    PostBundle\Controller\CommentController:
        bind:
            $eventDispatcher: '@event_dispatcher'
        tags: ['controller.service_arguments']

#   Fixtures
    PostBundle\DataFixtures\ORM\LoadTagData:
        tags: ['doctrine.fixture.orm']

    PostBundle\DataFixtures\ORM\LoadCommentData:
        tags: ['doctrine.fixture.orm']

    PostBundle\DataFixtures\ORM\LoadPostData:
        arguments: ['@slugger']
        tags: ['doctrine.fixture.orm']

#   Utils
    slugger:
        class: 'PostBundle\Utils\Slugger'

    markdown:
        class: 'PostBundle\Utils\Markdown'